/** \file
 * This file only contains utility stuff on top of the abstract syntax tree
 * structure generated by \ref tree-gen based on "syntactic.tree". Refer to
 * the cqasm::syntactic namespace documentation for more information.
 */

#pragma once

#include <sstream>
#include <string>

#include "libqasm/tree.hpp"

namespace cqasm::syntactic {

/**
 * Special/temporary string builder node, used to build strings from fragments
 * and escape sequences while parsing. This is abstracted out of the AST; it
 * should never appear after parsing completes.
 */
struct StringBuilder : public cqasm::tree::Base {
    std::ostringstream stream;

    /**
     * Pushes a string fragment into the string.
     */
    void push_string(const std::string& str);

    /**
     * Pushes an escape sequence into the string.
     */
    void push_escape(const std::string& escape);
};

}  // namespace cqasm::syntactic
