package:
  name: libqasm
  version: "{{ load_setup_py_data().version }}"

source:
  path: ../../.

build:
  number: 0
  script_env:
    - NPROCS

requirements:
  build:
    - {{ compiler('cxx') }}
    - setuptools
    - swig
    - cmake
    - flex # [not win]
    - bison # [not win]
    #- winflexbison # [win]
  host:
    - python
    - plumbum
    - delocate # [osx]
  run:
    - python

test:
  imports:
    - libQasm
  source_files:
    - src/tests
  requires:
    - pytest
  commands:
    - pytest src/tests

about:
  home: https://github.com/QuTech-Delft/libqasm
  license: Apache v2.0
