/* sample.h */

/* written by Douglas Jones, July 2010,
   based on pieces of cruncher,
     written in Pascal by Douglas Jones, March 1990
     rewritten in C, Jan 2007
*/

/* Output a random derivation from the grammar */

/*
 * The interface
 */

void sample(); /* write a sample string generated by grammar */
