properties([
  buildDiscarder(
    logRotator(
      artifactDaysToKeepStr: '',
      artifactNumToKeepStr: '',
      daysToKeepStr: '',
      numToKeepStr: '10'
    )
  )
])

pipeline {
  agent {
    kubernetes {
      label 'libqasm'
      yamlFile 'ci/manifest.yaml'
    }
  }
  stages {
    stage('Build') {
      steps {
        container('libqasm') {
          sh '''
            git submodule update --init --recursive &&
            cd qasm_flex_bison && mkdir build && cd build && cmake ../library && make
          '''
        }
      }
    }
    stage('Tests') {
      steps {
        container('libqasm') {
          sh '''
            cd qasm_flex_bison && cd build && make test
          '''
        }
      }
    }
  }
}
