properties([
  buildDiscarder(
    logRotator(
      artifactDaysToKeepStr: '',
      artifactNumToKeepStr: '',
      daysToKeepStr: '',
      numToKeepStr: '10'
    )
  )
])

pipeline {
  agent {
    kubernetes {
      label 'libqasm'
      yaml """
metadata:
  labels:
    test: libqasm
spec:
  containers:
  - name: libqasm
    image: qutech/libqasm:1.0.3
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: "512Mi"
      limits:
        memory: "512Mi"
  - name: jnlp
    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "256Mi"
  imagePullSecrets:
    - name: regcred
      """
    }
  }
  stages {
    stage('Build') {
      steps {
        container('libqasm') {
          sh '''
            apt-get install -y python3-venv
            git submodule update --init --recursive &&
            cd qasm_flex_bison && mkdir cbuild && cd cbuild && cmake ../library && make
          '''
        }
      }
    }
    stage('Tests') {
      steps {
        container('libqasm') {
          sh '''
            cd qasm_flex_bison && cd cbuild && make test &&
            cd .. && pwd && python3 -m venv env &&
            . ./env/bin/activate &&
            pip install . --upgrade &&
            python -m unittest discover -s tests/python -v
          '''
        }
      }
    }
  }
}
