/* A Bison parser, made by GNU Bison 3.7.4.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2020 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_CQASM_VERSION_MNT_C_PROJECTS_LIBQASM_BUILD_SRC_CQASM_VERSION_PARSER_HPP_INCLUDED
# define YY_CQASM_VERSION_MNT_C_PROJECTS_LIBQASM_BUILD_SRC_CQASM_VERSION_PARSER_HPP_INCLUDED
/* Debug traces.  */
#ifndef CQASM_VERSION_DEBUG
# if defined YYDEBUG
#if YYDEBUG
#   define CQASM_VERSION_DEBUG 1
#  else
#   define CQASM_VERSION_DEBUG 0
#  endif
# else /* ! defined YYDEBUG */
#  define CQASM_VERSION_DEBUG 0
# endif /* ! defined YYDEBUG */
#endif  /* ! defined CQASM_VERSION_DEBUG */
#if CQASM_VERSION_DEBUG
extern int cqasm_version_debug;
#endif
/* "%code requires" blocks.  */
#line 5 "src/cqasm-version-parser.y"

    /**
     * \file
     * Parser, generated by Bison.
     */
    #include <memory>
    #include <cstdio>
    #include <cstdint>
    #include <string>
    #include "cqasm-error.hpp"
    #include "cqasm-version.hpp"
    using namespace cqasm::version;
    typedef void* yyscan_t;

    #define YYSTYPE CQASM_VERSION_STYPE
    #define YYLTYPE CQASM_VERSION_LTYPE


#line 76 "src/cqasm-version-parser.hpp"

/* Token kinds.  */
#ifndef CQASM_VERSION_TOKENTYPE
# define CQASM_VERSION_TOKENTYPE
  enum cqasm_version_tokentype
  {
    CQASM_VERSION_EMPTY = -2,
    CQASM_VERSION_EOF = 0,         /* "end of file"  */
    CQASM_VERSION_error = 256,     /* error  */
    CQASM_VERSION_UNDEF = 257,     /* "invalid token"  */
    VERSION = 258,                 /* VERSION  */
    INT_LITERAL = 259,             /* INT_LITERAL  */
    UNKNOWN = 260,                 /* UNKNOWN  */
    END_OF_FILE = 261              /* END_OF_FILE  */
  };
  typedef enum cqasm_version_tokentype cqasm_version_token_kind_t;
#endif

/* Value type.  */
#if ! defined CQASM_VERSION_STYPE && ! defined CQASM_VERSION_STYPE_IS_DECLARED
union CQASM_VERSION_STYPE
{
#line 34 "src/cqasm-version-parser.y"

    char            *str;
    Version         *vers;

#line 104 "src/cqasm-version-parser.hpp"

};
typedef union CQASM_VERSION_STYPE CQASM_VERSION_STYPE;
# define CQASM_VERSION_STYPE_IS_TRIVIAL 1
# define CQASM_VERSION_STYPE_IS_DECLARED 1
#endif

/* Location type.  */
#if ! defined CQASM_VERSION_LTYPE && ! defined CQASM_VERSION_LTYPE_IS_DECLARED
typedef struct CQASM_VERSION_LTYPE CQASM_VERSION_LTYPE;
struct CQASM_VERSION_LTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
};
# define CQASM_VERSION_LTYPE_IS_DECLARED 1
# define CQASM_VERSION_LTYPE_IS_TRIVIAL 1
#endif



int cqasm_version_parse (yyscan_t scanner, const std::string &filename, cqasm::version::Version &version);

#endif /* !YY_CQASM_VERSION_MNT_C_PROJECTS_LIBQASM_BUILD_SRC_CQASM_VERSION_PARSER_HPP_INCLUDED  */
