name: Doc

on:
  pull_request:
  push:
    branches:
      - develop
      - master
  release:
    types:
      - created

jobs:
  publish-github-pages:
    name: Publish GitHub pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip -r requirements.txt
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages:gh-pages
      - name: Add mkdocs custom handlers folder to env
        run: |
          echo "PYTHONPATH=./scripts/python" >> $GITHUB_ENV
      - name: Dry run
        if: github.event_name == 'pull_request'
        run: |          
          mkdocs build
      - name: Upload and tag as latest with every push to develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
          mike deploy --push latest
          mike set-default --push latest
      - name: Upload and tag as git tag with every release creation on master branch
        if: github.event_name == 'release' && github.event.action == 'created'
        run: |
          mike deploy --push ${{ github.ref }}
          mike set-default --push latest
